---
name: Cleanup Branches

# This workflow removes all branches except main
# Run manually when needed to clean up old branches

on:
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete all branches except main
        run: |
          # Get all remote branches except main
          branches=$(git branch -r | grep -v '\->' | \
            grep -v 'main$' | sed 's/origin\///')

          echo "Branches to delete:"
          echo "$branches"

          # Delete each branch
          for branch in $branches; do
            echo "Deleting branch: $branch"
            git push origin --delete "$branch" || \
              echo "Failed to delete $branch"
          done

          echo "Branch cleanup completed!"
